---
driver:
  name: vagrant

platforms:
  - name: centos-7
    driver:
      box: bento/centos-7

provisioner:
  name: chef_solo
  require_chef_omnibus: "13.1.31"

verifier:
  name: inspec

suites:
  - name: default
    run_list:
        - docker-systemd
    attributes:
      docker-systemd:
        containers:
          redis:
            image: redis
            tag: '4'
            options:
              publish: "8888:6379"
    verifier:
      inspec_tests:
        - tests/docker-systemd.rb
