---
driver:
  name: dokken
  chef_version: "12.7.2"
  chef_image: someara/chef
  privileged: true
  volumes: [
    '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
  ]

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

verifier:
  name: inspec

suites:
  - name: default
    run_list:
        - docker-systemd
    attributes:
      docker-systemd:
        containers:
          redis:
            image: redis
            tag: '4'
            options:
              publish: "8888:6379"
    verifier:
      inspec_tests:
        - tests/docker-systemd.rb
