language: ruby
dist: trusty

matrix:
  include:
    - rvm: 2.4
      env: suite=centos-7

sudo: required
services: docker

before_script:
  - make install
  - make bundle
#  - make style

script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen test "$suite"
