version: '{build}-{branch}'
os: Default Azure
platform:
  - x64

init:
- ps: |
    [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }

install:
- ps: |
    choco install virtualbox
    choco install vagrant
    choco install make
    cd $env:APPVEYOR_BUILD_FOLDER
- refreshenv
- set PATH=C:\Ruby24-x64\bin;%PATH%
- ruby -v
- vagrant -v
- VBoxManage -v
- ssh -V
build_script:
- ps: Test-NetConnection google.com -Port 80
- make bundle
#- vagrant up || ssh vagrant@127.0.0.1 -p 2222 -i .vagrant\machines\default\virtualbox\private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv -C "pwd"
#- vagrant ssh -c "uname -a"
test: off
