version: '{build}-{branch}'
os: Windows Server 2012
platform:
  - x64
init:
- ps: |
    mkdir C:\Users\appveyor\.vagrant.d | Out-Null
    echo @'
    Vagrant::configure('2') do |config|
      config.vm.boot_timeout = 1020
    end
    '@ | Out-File -encoding UTF8 C:\Users\appveyor\.vagrant.d\Vagrantfile
- ps: |
    mkdir C:\downloads | Out-Null
    cd C:\downloads
    Start-FileDownload "https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.msi"
    Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_1.7.2.msi /qb TARGETDIR=C:\Vagrant-2.0.3" -Wait
    Start-FileDownload "https://download.virtualbox.org/virtualbox/5.2.8/VirtualBox-5.2.8-121009-Win.exe"
    Start-Process -FilePath "VirtualBox-5.2.8-121009-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox-5.2.8" -Wait
    cd $env:APPVEYOR_BUILD_FOLDER
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }
install:
- set PATH=C:\Vagrant-2.0.3\HashiCorp\Vagrant\bin;C:\VBox-5.2.8;%PATH%
- set PATH=C:\Ruby24-x64\bin;%PATH%
- vagrant -v
- VBoxManage -v
- ssh -V
- ipconfig /all
build_script:
- ps: Test-NetConnection google.com -Port 80
#- vagrant up || ssh vagrant@127.0.0.1 -p 2222 -i .vagrant\machines\default\virtualbox\private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv -C "pwd"
#- vagrant ssh -c "uname -a"
test: off
